### ISSUE TITLE
Hosting website in GitHub Pages

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [FemiOluwadamilola/moviewebsite#1]
### Description

It would be brilliant if the website could be hosted in GitHub Pages. This way, people will get to see how the website looks like without needing to download the code.

### Steps to achieve this

- On this repository, go to the settings.
- Scroll down to **GitHub Pages** section.
<img width="926" alt="Screen Shot 2021-01-15 at 15 05 38" src="https://user-images.githubusercontent.com/61970868/104717703-229be700-5743-11eb-82b3-af6200659b19.png">

- Change the **Source** to **master branch**
- Choose the folder to point at **public** folder and save.
- Copy the link that appeared there and add it to your README file.
- Celebrate.🎉

**Comment by FemiOluwadamilola** [comment]
thanks @Rahma-AlWadhahi 
- [x] now hosted on github

**Comment by Rahma-AlWadhahi** [comment]
### Well Done!! 🎉 
I didn't notice that you have already added it in your README file 😅 

It looks like it is pointing to the **root** folder in the **master branch**.
The URL to your website should be https://femioluwadamilola.github.io/moviewebsite/

<img width="572" alt="Screen Shot 2021-02-28 at 14 56 44" src="https://user-images.githubusercontent.com/61970868/109415998-2f178e80-79d5-11eb-94f8-1ac62a49a62e.png">

Go back to **GitHub Pages** section mentioned above and see (do you have _/public_ folder listed?)
If the answer is No, let me know so that I can suggest something else in a new issue

**Comment by Rahma-AlWadhahi** [comment]
You can go ahead and close this issue because it is resolved 😄
