### ISSUE TITLE
Could you make README more descriptive?

### ISSUE THREAD

**Issue by Rahma-AlWadhahi** [FemiOluwadamilola/moviewebsite#2]
### Description

The current README file does not have enough information to let the people know more about what the project is doing.

### Question
Could you please tell us in the README file:
1. What is this project about?
2. What are the goals of the project?
3. What are the technologies used?
4. ...

**Comment by FemiOluwadamilola** [comment]
**README FILE UPDATED**
- [x] Info about project
- [x] goal of project
- [x] Technologies used

**Comment by FemiOluwadamilola** [comment]
thanks for the contribution I'm really grateful
